# Generated by Django 2.2.4 on 2019-08-10 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tevello', '0002_destination_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.IntegerField(max_length=2)),
                ('month', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=50)),
                ('tag', models.CharField(max_length=50)),
                ('des', models.TextField()),
                ('image', models.ImageField(upload_to='post')),
            ],
        ),
    ]
