# Generated by Django 2.2.4 on 2019-08-10 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tevello', '0003_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.IntegerField(),
        ),
    ]
